
import React, { useState, useEffect } from 'react';
import { X, Sparkles, Loader2, Check } from 'lucide-react';
import { GoogleGenAI, Type } from '@google/genai';
import { useData } from '../context/DataContext';
import type { Campaign, Task } from '../types';

interface AICampaignModalProps {
  isOpen: boolean;
  onClose: () => void;
  initialPrompt?: string;
}

// Define the shape of the AI response
interface AIResponse {
  campaignName: string;
  strategyNotes: string;
  tasks: string[];
}

export const AICampaignModal: React.FC<AICampaignModalProps> = ({ isOpen, onClose, initialPrompt }) => {
  const { addCampaign, addTasks } = useData();
  const [step, setStep] = useState<'input' | 'loading' | 'review'>('input');
  
  // Input State
  const [topic, setTopic] = useState('');
  const [brand, setBrand] = useState('');
  const [platform, setPlatform] = useState('Instagram');

  // Generated Data State
  const [generatedData, setGeneratedData] = useState<AIResponse | null>(null);

  // Auto-fill prompt if provided
  useEffect(() => {
    if (initialPrompt && isOpen) {
       // Heuristic to fill fields based on prompt for demo feel
       setTopic(initialPrompt); 
    }
  }, [initialPrompt, isOpen]);

  if (!isOpen) return null;

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setStep('loading');

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      
      const prompt = `
        You are an expert social media strategist. 
        Create a content campaign for a brand called "${brand || 'My Personal Brand'}" focusing on "${topic}" for the platform "${platform}".
        
        Return a JSON object with:
        1. A creative campaign name.
        2. A short paragraph of strategy notes (vibes, hook ideas).
        3. A list of 4-6 specific actionable tasks (e.g. "Scripting", "Filming B-Roll", "Editing").
      `;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              campaignName: { type: Type.STRING },
              strategyNotes: { type: Type.STRING },
              tasks: { 
                type: Type.ARRAY, 
                items: { type: Type.STRING } 
              }
            }
          }
        }
      });

      const text = response.text;
      if (text) {
        setGeneratedData(JSON.parse(text));
        setStep('review');
      } else {
        throw new Error("No content generated");
      }

    } catch (error) {
      console.error("AI Generation failed", error);
      setStep('input');
    }
  };

  const handleSave = () => {
    if (!generatedData) return;

    const campaignId = Date.now().toString();
    const today = new Date();
    const twoWeeksLater = new Date(today.getTime() + 14 * 24 * 60 * 60 * 1000);
    const dueDateStr = twoWeeksLater.toISOString().split('T')[0];

    // 1. Create Campaign
    const newCampaign: Campaign = {
      id: campaignId,
      name: generatedData.campaignName,
      brand: brand || 'Personal Project',
      status: 'Planned',
      primaryDueDate: dueDateStr,
      notes: generatedData.strategyNotes,
    };

    // 2. Create Tasks
    const newTasks: Task[] = generatedData.tasks.map((taskTitle, index) => {
      // Stagger dates slightly
      const taskDate = new Date(today.getTime() + (index + 1) * 2 * 24 * 60 * 60 * 1000);
      return {
        id: `${campaignId}-t${index}`,
        title: taskTitle,
        campaignId: campaignId,
        status: 'To Do',
        dueDate: taskDate.toISOString().split('T')[0],
        notes: 'Generated by AI Strategist',
      };
    });

    addCampaign(newCampaign);
    addTasks(newTasks);
    
    // Reset and close
    setTopic('');
    setBrand('');
    setPlatform('Instagram');
    setGeneratedData(null);
    setStep('input');
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-70 backdrop-blur-sm p-4">
      <div className="bg-surface border border-borderColor w-full max-w-lg rounded-xl shadow-2xl overflow-hidden relative transition-colors">
        
        {/* Header */}
        <div className="flex justify-between items-center p-4 border-b border-borderColor bg-gradient-to-r from-surface to-surfaceLight/50">
          <div className="flex items-center gap-2">
            <Sparkles className="text-accent" size={20} />
            <h3 className="text-xl font-semibold text-textMain">AI Campaign Strategist</h3>
          </div>
          <button onClick={onClose} className="text-textMuted hover:text-textMain transition-colors">
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          {step === 'input' && (
            <form onSubmit={handleGenerate} className="space-y-4">
              <p className="text-textMuted text-sm mb-4">
                Tell us a bit about what you want to create, and Gemini will generate a full project plan with tasks.
              </p>
              <div>
                <label className="block text-sm font-medium text-textMuted mb-1">Brand Name (Optional)</label>
                <input 
                  type="text" 
                  className="w-full bg-surfaceLight border border-borderColor rounded-lg p-3 text-textMain focus:ring-2 focus:ring-accent outline-none"
                  placeholder="e.g. Nike, Sephora (Leave blank for generic)"
                  value={brand}
                  onChange={(e) => setBrand(e.target.value)}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-textMuted mb-1">What are you creating?</label>
                <input 
                  required
                  type="text" 
                  className="w-full bg-surfaceLight border border-borderColor rounded-lg p-3 text-textMain focus:ring-2 focus:ring-accent outline-none"
                  placeholder="e.g. Summer collection, New skincare routine"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-textMuted mb-1">Platform</label>
                <select 
                  className="w-full bg-surfaceLight border border-borderColor rounded-lg p-3 text-textMain focus:ring-2 focus:ring-accent outline-none"
                  value={platform}
                  onChange={(e) => setPlatform(e.target.value)}
                >
                  <option value="Instagram">Instagram Reels</option>
                  <option value="TikTok">TikTok</option>
                  <option value="YouTube">YouTube Shorts</option>
                  <option value="LinkedIn">LinkedIn</option>
                </select>
              </div>
              <button 
                type="submit" 
                className="w-full py-3 bg-gradient-to-r from-accent to-pink-600 hover:from-accentHover hover:to-pink-700 text-white font-semibold rounded-lg transition-all shadow-lg shadow-accent/20 flex items-center justify-center gap-2 mt-2"
              >
                <Sparkles size={18} /> Generate Plan
              </button>
            </form>
          )}

          {step === 'loading' && (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <Loader2 className="w-12 h-12 text-accent animate-spin mb-4" />
              <h4 className="text-xl font-bold text-textMain">Brewing ideas...</h4>
              <p className="text-textMuted mt-2">Gemini is analyzing the brand voice and creating tasks.</p>
            </div>
          )}

          {step === 'review' && generatedData && (
            <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
              <div className="bg-surfaceLight/30 rounded-lg p-4 border border-borderColor">
                <span className="text-xs font-bold text-accent uppercase tracking-wider">Campaign Name</span>
                <h3 className="text-lg font-bold text-textMain mt-1">{generatedData.campaignName}</h3>
              </div>
              
              <div className="bg-surfaceLight/30 rounded-lg p-4 border border-borderColor">
                <span className="text-xs font-bold text-textMuted uppercase tracking-wider">Strategy</span>
                <p className="text-sm text-textMain mt-1 leading-relaxed">{generatedData.strategyNotes}</p>
              </div>

              <div>
                <span className="text-xs font-bold text-textMuted uppercase tracking-wider mb-2 block">Generated Tasks</span>
                <div className="space-y-2 max-h-40 overflow-y-auto pr-2 custom-scrollbar">
                  {generatedData.tasks.map((task, i) => (
                    <div key={i} className="flex items-center gap-3 p-2 rounded bg-surfaceLight/20 border border-borderColor">
                      <div className="w-6 h-6 rounded-full bg-accent/20 flex items-center justify-center text-accent text-xs font-bold">
                        {i + 1}
                      </div>
                      <span className="text-sm text-textMain">{task}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex gap-3 mt-6">
                <button 
                  onClick={() => setStep('input')}
                  className="flex-1 py-3 bg-surfaceLight hover:bg-surface text-textMain font-medium rounded-lg transition-colors border border-borderColor"
                >
                  Back
                </button>
                <button 
                  onClick={handleSave}
                  className="flex-1 py-3 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition-colors shadow-lg shadow-green-900/20 flex items-center justify-center gap-2"
                >
                  <Check size={18} /> Accept & Create
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
